'use client';

import Image from 'next/image';
import { Navbar } from '@/components/layout/Navbar';
import { Footer } from '@/components/layout/Footer';
import { useMarket } from '@/lib/marketContext';

const WHAT_WE_DO = [
  {
    icon: '🌐',
    title: 'Global-Market Coverage',
    tag: 'Worldwide Traded Instruments',
    desc: 'Seamless analysis across traded instruments around the globe.',
  },
  {
    icon: '🤖',
    title: 'AI-Driven Analytics',
    tag: 'Machine Learning',
    desc: 'Advanced machine learning algorithms that spot anomalies, chart patterns, and sentiment shifts before they become mainstream news.',
  },
];

const MI_EDGE = [
  {
    icon: '🛡️',
    title: 'Battle-Tested DNA',
    tag: 'Decades of Lineage',
    desc: 'Built on understanding of decades of institutional trading, risk management, and quantitative strategy.',
  },
  {
    icon: '🌍',
    title: 'Global Markets Presence',
    tag: 'Cross-Border Feed',
    desc: 'Instant, AI-driven cross-border intelligence across major financial hubs.',
  },
  {
    icon: '⚡',
    title: 'Unfair Advantage',
    tag: 'Alpha Detection',
    desc: 'High-precision algorithmic insights that detect alpha before the markets wake up.',
  },
  {
    icon: '⏱️',
    title: 'High-Speed Scalping',
    tag: 'Sub-Minute Routing',
    desc: 'Sub-minute liquidity routing and immediate order-book anomaly detection.',
  },
  {
    icon: '📊',
    title: 'Intraday Momentum',
    tag: 'Volatility Breakouts',
    desc: 'Real-time volume spikes and volatility breakouts across both execution time zones.',
  },
  {
    icon: '🌊',
    title: 'Swing Trading',
    tag: 'Macro ML Forecasts',
    desc: 'Multi-day trend predictions driven by macro sentiment shifts and machine learning.',
  },
  {
    icon: '🎯',
    title: 'Options Architecture',
    tag: 'Derivatives & IV',
    desc: 'Advanced implied volatility analytics, unusual options activity tracking, and dynamic spread modelling.',
  },
  {
    icon: '💎',
    title: 'Long-Term Alpha',
    tag: 'Algorithmic Screener',
    desc: 'Algorithmic fundamental screening to identify deeply mispriced, high-growth equity assets.',
  },
];

const REGIONS = [
  {
    flag: '🇺🇸',
    name: 'USA — NYSE / NASDAQ',
    city: 'New York, USA',
    description: 'Direct optical interconnects to Wall Street and New Jersey data centers with institutional microstructure coverage across the NYSE, NASDAQ, S&P 500, NASDAQ 100, and mega-cap equity derivatives.',
    instruments: 'S&P 500, NASDAQ 100, DOW JONES, NVDA, AAPL, MSFT, TSLA, AMZN',
  },
  {
    flag: '🇮🇳',
    name: 'India — NSE / BSE (HQ)',
    city: 'Chennai, Tamil Nadu',
    description: 'Global engineering headquarters in Chennai with full coverage of the National Stock Exchange (NSE) and Bombay Stock Exchange (BSE), including all F&O instruments, NIFTY 50, BANK NIFTY, MIDCAP 150, and sectoral indices.',
    instruments: 'NIFTY 50, BANK NIFTY, SENSEX, NIFTY IT, NIFTY PHARMA, NIFTY AUTO',
  },
  {
    flag: '🇦🇪',
    name: 'UAE — DFM / ADX',
    city: 'Dubai, UAE',
    description: 'Comprehensive coverage of the Dubai Financial Market (DFM) and Abu Dhabi Securities Exchange (ADX), including GCC blue chips and DIFC-listed instruments.',
    instruments: 'DFMGI, ADXGI, EMAAR, FAB, DEWA, ALDAR, ETISALAT',
  },
];

const DISCLAIMER_TERMS = [
  {
    number: '01',
    title: 'For Informational & Study Purposes Only',
    text: 'MI 007 (a brand of Synthetix Analytics) is a technology platform provided strictly for general informational and study purposes. The information, reports, and AI-generated insights provided do not constitute investment, legal, tax, or accounting advice. MI 007 is not a licensed securities dealer, broker, investment adviser, or financial service provider. We strongly urge you to consult with a licensed financial professional before making any investment decisions.',
  },
  {
    number: '02',
    title: 'No Recommendations or Endorsements',
    text: 'Nothing provided by this service represents a recommendation to buy, sell, or hold any stock or financial instrument. The data and AI-generated inputs are indicative only and do not necessarily reflect the views of Synthetix Analytics or its employees.',
  },
  {
    number: '03',
    title: 'Data Accuracy & AI Limitations',
    text: 'Our reports and website inputs are generated by modern artificial intelligence tools using data from third-party suppliers. This information has not been independently verified. Please note that data may be delayed, may not be real-time, and is subject to the reporting cycles (quarterly/annual) of the respective companies. All information is provided "AS IS," and we do not guarantee its accuracy, completeness, or reliability.',
  },
  {
    number: '04',
    title: 'Assumption of Risk & Liability',
    text: 'Trading and investing involve significant risk. You alone assume sole responsibility for any investment decisions and their outcomes. Neither Synthetix Analytics, nor its affiliates, officers, or service providers, shall be held liable for any financial loss or results occurring from the use of our information.',
  },
  {
    number: '05',
    title: 'Intellectual Property',
    text: 'All content, charts, and data reports are the intellectual property of Synthetix Analytics or its providers. This information is for your personal use only. It is strictly prohibited to reproduce, publish, modify, or distribute this data without our explicit prior written permission.',
  },
];

export default function AboutPage() {
  const { market, setMarket } = useMarket();

  return (
    <>
      <Navbar market={market} onMarketChange={setMarket} />

      <main className="min-h-screen pt-[88px] relative z-10 bg-transparent">
        {/* ── Hero ── */}
        <section className="py-20 lg:py-24">
          <div className="mx-auto max-w-4xl px-6 text-center">
            {/* Tech Platform / Study Notice Pill */}
            <div className="inline-flex items-center gap-2 px-3.5 py-1 rounded-full border page-section-pill mb-3 shadow-xs">
              <span className="w-2 h-2 rounded-full bg-emerald-600 animate-pulse" />
              <span className="mono text-[13px] tracking-[0.25em] uppercase font-black page-section-pill-text">
                01 // STUDY &amp; RESEARCH TECHNOLOGY PLATFORM
              </span>
            </div>
            
            <h1 className="text-2xl xs:text-3xl sm:text-4xl md:text-5xl lg:text-6xl font-black tracking-tight mb-4 page-heading flex flex-col items-center justify-center gap-1">
              <span>Welcome to</span>
              <span className="whitespace-nowrap font-extrabold text-emerald-600">
                Market Intelligence - 007
              </span>
            </h1>

            <p className="text-[17px] sm:text-[19px] max-w-2xl mx-auto leading-relaxed font-medium page-subtitle mb-4">
              The premier market intelligence platform engineered to revolutionize how you navigate markets.
            </p>

            <p className="text-[15px] sm:text-[16px] max-w-2xl mx-auto leading-relaxed font-normal page-subtitle mb-8 opacity-90">
              Market Intelligence - 007 delivers institutional-grade market intelligence directly to retail investors, day traders, and portfolio managers worldwide.
            </p>

            {/* Informational & Risk Disclaimer Banner */}
            <div className="mx-auto max-w-2xl rounded-2xl border inst-card p-4 shadow-md text-left flex items-start gap-3">
              <span className="text-xl shrink-0 mt-0.5">ℹ️</span>
              <p className="text-xs sm:text-[13px] inst-card-text leading-relaxed font-medium">
                <strong className="font-bold text-emerald-500">Important Notice:</strong> Market Intelligence - 007 is a technology platform built purely for the purpose of study and information, empowering users to make their own decisions at their own risks.
              </p>
            </div>
          </div>
        </section>

        {/* ── Who We Are ── */}
        <section className="mx-auto max-w-5xl px-6 py-20">
          <div className="rounded-3xl border-2 inst-card p-8 sm:p-12 shadow-xl relative overflow-hidden">
            <div className="relative z-10 max-w-3xl">
              <div className="inline-flex items-center gap-2 px-3.5 py-1 rounded-full border page-section-pill mb-4 shadow-xs">
                <span className="w-2 h-2 rounded-full bg-cyan-500 animate-pulse" />
                <span className="mono text-[13px] tracking-[0.25em] uppercase font-black page-section-pill-text">
                  OUR GENESIS
                </span>
              </div>
              <h2 className="text-3xl sm:text-4xl md:text-5xl font-black tracking-tight mb-4 inst-card-text">
                Who We Are
              </h2>
              <p className="text-[17px] sm:text-[19px] leading-relaxed font-medium inst-card-text mb-4 opacity-95">
                MI-007 was founded by a team of Quantitative Analysts, Data Scientists, Veteran Investors and Traders who shared a common problem which is the sheer volume of market noise.
              </p>
              <p className="text-[15px] sm:text-[16px] leading-relaxed font-normal inst-card-text-muted mb-4">
                Crucial insights are often buried under oceans of raw data, accessible only to Institutions of scale.
              </p>
              <p className="text-[16px] sm:text-[17px] text-emerald-500 font-bold leading-relaxed">
                We built MI-007 to level the playing field, providing intelligence across global markets to the common investors as well.
              </p>
            </div>

            <div className="mt-10 grid grid-cols-1 sm:grid-cols-3 gap-4 pt-8 border-t border-[var(--theme-card-border)]">
              <div className="p-4 rounded-2xl border inst-subcard shadow-xs">
                <div className="mono text-2xl sm:text-3xl font-black inst-card-text">Decades</div>
                <div className="text-xs inst-card-text-muted font-bold uppercase tracking-wider mt-1">Quant &amp; Trading Heritage</div>
              </div>
              <div className="p-4 rounded-2xl border inst-subcard shadow-xs">
                <div className="mono text-2xl sm:text-3xl font-black text-emerald-500">Global</div>
                <div className="text-xs inst-card-text-muted font-bold uppercase tracking-wider mt-1">Cross-Border Data</div>
              </div>
              <div className="p-4 rounded-2xl border inst-subcard shadow-xs">
                <div className="mono text-2xl sm:text-3xl font-black text-sky-400">Fair Game</div>
                <div className="text-xs inst-card-text-muted font-bold uppercase tracking-wider mt-1">Level Playing Field</div>
              </div>
            </div>
          </div>
        </section>

        {/* ── What We Do ── */}
        <section className="mx-auto max-w-6xl px-6 py-20">
          <div className="mb-12 text-center max-w-3xl mx-auto">
            <div className="inline-flex items-center gap-2 px-3.5 py-1 rounded-full border page-section-pill mb-3 shadow-xs">
              <span className="w-2 h-2 rounded-full bg-emerald-500 animate-pulse" />
              <span className="mono text-[13px] tracking-[0.25em] uppercase font-black page-section-pill-text">
                CONTINUOUS EXECUTION
              </span>
            </div>
            <h2 className="text-3xl sm:text-4xl md:text-5xl font-black tracking-tight mb-3 page-heading">What We Do</h2>
            <p className="text-[17px] sm:text-[19px] max-w-2xl mx-auto leading-relaxed font-medium page-subtitle">
              We track, analyse, and decode market movements around the clock. Whether you are looking for momentum shifts in Wall Street tech giants or breakout trends in Dalal Street blue-chips, MI-007 is your eyes and ears on the ground.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-6 max-w-4xl mx-auto">
            {WHAT_WE_DO.map(({ icon, title, tag, desc }) => (
              <div
                key={title}
                className="rounded-2xl border-2 inst-card p-7 hover:shadow-xl transition-all flex flex-col justify-between"
              >
                <div>
                  <div className="flex items-center justify-between mb-4">
                    <span className="text-3xl">{icon}</span>
                    <span className="text-[11px] mono font-bold px-2.5 py-0.5 rounded-full border border-[var(--theme-card-border)] bg-[var(--theme-card-surface)] inst-card-text shadow-2xs">
                      {tag}
                    </span>
                  </div>
                  <h3 className="font-black inst-card-text text-xl mb-3 tracking-tight">{title}</h3>
                  <p className="text-[14px] inst-card-text-muted leading-relaxed font-medium">{desc}</p>
                </div>
              </div>
            ))}
          </div>
        </section>

        {/* ── Our Mission ── */}
        <section className="mx-auto max-w-5xl px-6 py-20">
          <div className="rounded-3xl border-2 inst-card p-8 sm:p-12 shadow-xl text-center">
            <div className="inline-flex items-center gap-2 px-3.5 py-1 rounded-full border page-section-pill mb-4 shadow-xs">
              <span className="w-2 h-2 rounded-full bg-emerald-500 animate-pulse" />
              <span className="mono text-[13px] tracking-[0.25em] uppercase font-black page-section-pill-text">
                CORE PURPOSE
              </span>
            </div>
            <h2 className="text-3xl sm:text-4xl md:text-5xl font-black tracking-tight mb-4 inst-card-text">
              Our Mission
            </h2>
            <h3 className="text-xl sm:text-2xl font-black text-emerald-500 mb-4">
              To democratize financial intelligence.
            </h3>
            <p className="text-[17px] sm:text-[19px] inst-card-text font-medium leading-relaxed max-w-3xl mx-auto mb-4">
              We believe that every investor deserves access to sharp, timely, and unbiased data.
            </p>
            <p className="text-[15px] sm:text-[16px] inst-card-text-muted font-normal leading-relaxed max-w-3xl mx-auto">
              Our Team and MI-007 are committed to empower you with the tools, clarity, and confidence to build long-term wealth.
            </p>
          </div>
        </section>

        {/* ── The MI-007 Edge ── */}
        <section className="mx-auto max-w-6xl px-6 py-20">
          <div className="mb-12 text-center max-w-3xl mx-auto">
            <div className="inline-flex items-center gap-2 px-3.5 py-1 rounded-full border page-section-pill mb-3 shadow-xs">
              <span className="w-2 h-2 rounded-full bg-cyan-500 animate-pulse" />
              <span className="mono text-[13px] tracking-[0.25em] uppercase font-black page-section-pill-text">
                INSTITUTIONAL CAPABILITIES
              </span>
            </div>
            <h2 className="text-3xl sm:text-4xl md:text-5xl font-black tracking-tight mb-3 page-heading">The MI-007 Edge</h2>
            <p className="text-[17px] sm:text-[19px] max-w-2xl mx-auto leading-relaxed font-medium page-subtitle">
              Eight tactical pillars designed to strip away noise and reveal actionable alpha.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-5">
            {MI_EDGE.map(({ icon, title, tag, desc }) => (
              <div
                key={title}
                className="rounded-2xl border-2 inst-card p-6 hover:shadow-xl hover:scale-[1.02] transition-all flex flex-col justify-between"
              >
                <div>
                  <div className="flex items-center justify-between mb-3">
                    <span className="text-2xl p-2 rounded-xl border border-[var(--theme-card-border)] bg-[var(--theme-card-surface)] inline-flex items-center justify-center">
                      {icon}
                    </span>
                    <span className="text-[10px] mono font-bold px-2 py-0.5 rounded-md border border-[var(--theme-card-border)] bg-[var(--theme-card-surface)] inst-card-text">
                      {tag}
                    </span>
                  </div>
                  <h3 className="font-bold inst-card-text text-base mb-2">{title}</h3>
                  <p className="text-[13px] inst-card-text-muted leading-relaxed font-medium">{desc}</p>
                </div>
              </div>
            ))}
          </div>
        </section>

        {/* ── Multi-Region Coverage ── */}
        <section className="mx-auto max-w-6xl px-6 py-20">
          <div className="mb-12 text-center">
            <div className="inline-flex items-center gap-2 px-3.5 py-1 rounded-full border page-section-pill mb-3 shadow-xs">
              <span className="w-2 h-2 rounded-full bg-amber-500 animate-pulse" />
              <span className="mono text-[13px] tracking-[0.25em] uppercase font-black page-section-pill-text">
                GLOBAL TRADING CORRIDORS
              </span>
            </div>
            <h2 className="text-3xl sm:text-4xl md:text-5xl font-black tracking-tight mb-3 page-heading">Multi-Region Coverage</h2>
            <p className="text-[17px] sm:text-[19px] max-w-2xl mx-auto leading-relaxed font-medium page-subtitle">
              Co-located infrastructure across US, Indian, and Gulf financial hubs.
            </p>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-5 max-w-6xl mx-auto">
            {REGIONS.map(({ flag, name, city, description, instruments }) => (
              <div key={name} className="rounded-2xl border-2 inst-card p-6 flex flex-col gap-4 shadow-xl">
                <div className="flex items-start gap-3">
                  <span className="text-3xl">{flag}</span>
                  <div>
                    <div className="font-bold inst-card-text text-[15px]">{name}</div>
                    <div className="text-[11px] inst-card-text-muted mono font-medium">📍 {city}</div>
                  </div>
                </div>
                <p className="text-[12.5px] inst-card-text-muted leading-relaxed">{description}</p>
                <div className="rounded-lg border border-[var(--theme-card-border)] bg-[var(--theme-card-surface)] p-3">
                  <div className="text-[10px] inst-card-text-muted font-bold mono tracking-widest uppercase mb-1.5">Instruments</div>
                  <div className="text-[12px] inst-card-text mono font-medium leading-relaxed">{instruments}</div>
                </div>
              </div>
            ))}
          </div>
        </section>

        {/* ── Quant Philosophy ── */}
        <section className="py-16">
          <div className="mx-auto max-w-3xl px-6 text-center">
            <div className="mb-5 flex justify-center">
              <div className="h-16 w-16 rounded-2xl border border-sky-300/80 overflow-hidden shadow-lg shadow-sky-500/20 flex items-center justify-center">
                <Image
                  src="/images/logo-falcon-gradient.png"
                  alt="Market Intelligence - 007"
                  width={64}
                  height={64}
                  className="w-full h-full object-cover"
                />
              </div>
            </div>
            <blockquote className="text-lg md:text-xl italic font-semibold page-heading leading-relaxed">
              &ldquo;The best trading decisions are made not on emotion, but on the precise mathematical
              analysis of price, volume, and order flow — across every market on earth.&rdquo;
            </blockquote>
            <p className="mt-4 page-subtitle text-sm font-medium">— Market Intelligence - 007 Leadership Team</p>
          </div>
        </section>

        {/* ── Disclaimer & Terms of Use ── */}
        <section className="py-20">
          <div className="mx-auto max-w-5xl px-6">
            <div className="mb-12 text-center max-w-3xl mx-auto">
              <div className="inline-flex items-center gap-2 px-3.5 py-1 rounded-full border page-section-pill mb-3 shadow-xs">
                <span className="w-2 h-2 rounded-full bg-amber-600 animate-pulse" />
                <span className="mono text-[13px] tracking-[0.25em] uppercase font-black page-section-pill-text">
                  COMPLIANCE &amp; LEGAL FRAMEWORK
                </span>
              </div>
              <h2 className="text-3xl sm:text-4xl md:text-5xl font-black tracking-tight mb-3 page-heading">
                Disclaimer &amp; Terms of Use
              </h2>
              <p className="text-[17px] sm:text-[19px] max-w-2xl mx-auto leading-relaxed font-medium page-subtitle">
                Important disclosures regarding data limitations, non-advisory status, and user risk assumption.
              </p>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
              {DISCLAIMER_TERMS.map(({ number, title, text }) => (
                <div
                  key={number}
                  className={`rounded-2xl border-2 inst-card p-6 sm:p-7 shadow-xl hover:shadow-2xl transition-all ${
                    number === '05' ? 'md:col-span-2' : ''
                  }`}
                >
                  <div className="flex items-center gap-3 mb-3">
                    <span className="mono text-xs font-black px-2.5 py-1 rounded-md border border-[var(--theme-card-border)] bg-[var(--theme-card-surface)] inst-card-text">
                      {number}
                    </span>
                    <h3 className="text-base sm:text-lg font-bold inst-card-text tracking-tight">
                      {title}
                    </h3>
                  </div>
                  <p className="text-xs sm:text-[13.5px] inst-card-text-muted leading-relaxed font-medium">
                    {text}
                  </p>
                </div>
              ))}
            </div>

            <div className="mt-8 rounded-xl border border-[var(--theme-card-border)] bg-[var(--theme-card-surface)] p-4 text-center">
              <p className="text-xs mono inst-card-text-muted font-semibold">
                By accessing MI-007, you acknowledge that you have read, understood, and agreed to these terms.
              </p>
            </div>
          </div>
        </section>
      </main>

      <Footer />
    </>
  );
}
